image: node:latest

cache:
  paths:
    - node_modules/

pages:
  script:
    - cd dapp
    - npm install
    - npm run build
    - mv build ../public
  artifacts:
    paths:
      - public
  only:
    - master
