/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as priceOracle from "./PriceOracle";
export type { priceOracle };
import type * as resolutionManager from "./ResolutionManager";
export type { resolutionManager };
import type * as shareholderRegistry from "./ShareholderRegistry";
export type { shareholderRegistry };
import type * as telediskoToken from "./TelediskoToken";
export type { telediskoToken };
import type * as voting from "./Voting";
export type { voting };
import type * as extensions from "./extensions";
export type { extensions };
import type * as mocks from "./mocks";
export type { mocks };
